/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.ui.educator;

import app.ui.*;
import javax.swing.JOptionPane;
import repositories.StudentRepository;
import services.StudentService;

/**
 *
 * @author x
 */
public class EducatorHomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private final StudentService studentService;

    public EducatorHomeFrame() {
        initComponents();
        this.studentService = new StudentRepository();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        educatorProfileButton = new javax.swing.JButton();
        notiButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        globalLearderBoardButton = new javax.swing.JButton();
        upcomingEventsButton = new javax.swing.JButton();
        createQuizButton = new javax.swing.JButton();
        createEventButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 360));

        jPanel1.setMaximumSize(new java.awt.Dimension(4000, 3000));
        jPanel1.setMinimumSize(new java.awt.Dimension(4000, 3000));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(4000, 3000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        educatorProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ui/educator/profileButton40.jpg"))); // NOI18N
        educatorProfileButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        educatorProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educatorProfileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(educatorProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 50, 50));

        notiButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        notiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ui/educator/notiB1.png"))); // NOI18N
        notiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notiButtonActionPerformed(evt);
            }
        });
        jPanel1.add(notiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 50, 50));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hacking The Future");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 600, 70));

        globalLearderBoardButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        globalLearderBoardButton.setText("Global Leaderboard");
        globalLearderBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                globalLearderBoardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(globalLearderBoardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        upcomingEventsButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        upcomingEventsButton.setText("Upcoming Events");
        upcomingEventsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upcomingEventsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(upcomingEventsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        createQuizButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        createQuizButton.setText("Create Quiz");
        createQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createQuizButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createQuizButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 700, -1, -1));

        createEventButton.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        createEventButton.setText("Create Event");
        jPanel1.add(createEventButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/ui/home1.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -180, 1760, 1260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 557, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2491, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notiButtonActionPerformed
        // TODO add your handling code here:
        NotificationFrame notificationFrame = new NotificationFrame();
        notificationFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_notiButtonActionPerformed

    private void createQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createQuizButtonActionPerformed
        // TODO add your handling code here:
        CreateQuizFrame createQuizFrame = new CreateQuizFrame();
        createQuizFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_createQuizButtonActionPerformed

    private void educatorProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educatorProfileButtonActionPerformed
        // TODO add your handling code here:
        EducatorProfileFrame educatorProfileFrame = new EducatorProfileFrame();
        educatorProfileFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_educatorProfileButtonActionPerformed

    private void globalLearderBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_globalLearderBoardButtonActionPerformed
        // TODO add your handling code here:
        GlobalLeaderBoard globalLeaderBoard = new GlobalLeaderBoard();
        globalLeaderBoard.setVisible(true);
        dispose();
    }//GEN-LAST:event_globalLearderBoardButtonActionPerformed

    private void upcomingEventsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upcomingEventsButtonActionPerformed
        // TODO add your handling code here:
        UpcomingEventFrame upcomingEventFrame = new UpcomingEventFrame();
        upcomingEventFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_upcomingEventsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EducatorHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EducatorHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EducatorHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EducatorHomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EducatorHomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton createEventButton;
    private javax.swing.JButton createQuizButton;
    private javax.swing.JButton educatorProfileButton;
    private javax.swing.JButton globalLearderBoardButton;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton notiButton;
    private javax.swing.JButton upcomingEventsButton;
    // End of variables declaration//GEN-END:variables
}
